version: "3.9"

services:
  helloworld:
    container_name: hello-world
    platform: linux/amd64         # linux/amd64 / linux/arm64/v8
    image: hello_world
    tty: true                     # false for `entrypoint` in Dockerfile
    stdin_open: true              # false for `entrypoint` in Dockerfile
    env_file:
      - ./.env
    environment:
      - PIP_DISABLE_PIP_VERSION_CHECK=off
    volumes:
      - .:/app
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    build:
      context: ./
      dockerfile: ./Dockerfile.web

networks:
  default:
    driver: bridge
